version: '3'
services:
  medical-clinic:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: km
      POSTGRES_PASSWORD: km1234
    volumes:
      - postgres-volume:/data
volumes:
  postgres-volume:
