version: '3'
services:
  medical-clinic:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8880:8880"
    environment:
      spring_datasource_url: jdbc:postgresql://db:5432/postgres
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: km
      POSTGRES_PASSWORD: km1234
    volumes:
      - postgres-volume:/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4_container
    ports:
      - "8888:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: user@gmail.com
        PGADMIN_DEFAULT_PASSWORD: sa1234
    volumes:
          - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-volume:
  local_pgdata:
  pgadmin-data:
